rename:
  rt: [Restriction, Type]
  shi502_reserved: [security, descriptor, length]
  shi503_reserved: [security, descriptor, length]
  shi1501_reserved: [security, descriptor, length]
  StringArray_r: [Char, String, Array]
  StringsArray_r: [Char, Strings, Array]
  i: [Int16]
  l: [Int32]
  b: [Bool]
  lpszA: [Char, String]
  bin: [Binary]
  lpszW: [String]
  lppszW: [Values]
  lppszA: [Values]
  lpi: [Values]
  lpb: [Value]
  lpbin: [Values]
  paStr: [Strings]
  lpguid: [GUID]
  ft: [Date, Time]
  MVi: [Int16, Array]
  MVl: [Int32, Array]
  MVszA: [Char, String, Array]
  MVbin: [Binary, Array]
  MVguid: [GUID, Array]
  MVszW: [String, Array]
  MVft: [Date, Time, Array]
  MId1: [M, ID1]
  MId2: [M, ID2]
  ab: [Value]
