---
- name: features | Installing Windows DHCP Server
  win_feature:
    name: DHCP
    state: present
    include_management_tools: yes
    include_sub_features: yes
  register: windows_dhcp_server
